### ISSUE TITLE
subtitles are not visible when enetering full screen mode

### ISSUE THREAD

**Issue by sylikon** [Joran-Dob/flutter_subtitle_wrapper#58]
Im using chewie controller,  with simple SubStitleWrapper configuration:

`SubTitleWrapper(
      videoPlayerController: _controller,
      subtitleController: subtitleController,
      subtitleStyle: SubtitleStyle(
      textColor: Colors.white,
      ),
      videoChild: Chewie(
        controller: chewieController,
      ),
    );`

When entering fullscreeen mode in video subtitles are gone.

**Comment by Chomroeun** [comment]
I also met this problem. anyone else can solved it?

**Comment by himsa** [comment]
@sylikon did you find any solution ?

**Comment by sylikon** [comment]
@Himsa It turned out I messed up with defining MaterialApp() in hierarchy (not on top and got two of those), so I guess problem was not related to SubTitleWrapper

**Comment by sumit-coder** [comment]
https://github.com/Joran-Dob/flutter_subtitle_wrapper/issues/1#issuecomment-1176170030

go to this  one

**Comment by Joran-Dob** [comment]
Hi, 

I overlooked this project for a bit! Trying to find some time this week to resolve some of the issues or provide some input. Thanks for the information 🚀

**Comment by shiyiya** [comment]
Any progress？
@Joran-Dob

**Comment by Joran-Dob** [comment]
Yes, thinking about a fix! Still trying to figure out an excellent solution for this package and will get back to you. Thinking of some video player-specific implementation with some add-on packages.

I also see something interesting here: https://github.com/Joran-Dob/flutter_subtitle_wrapper/issues/1#issuecomment-1176170030, so I might look into this also a bit.

**Comment by shiyiya** [comment]
> Yes, thinking about a fix! Still trying to figure out an excellent solution for this package and will get back to you. Thinking of some video player-specific implementation with some add-on packages.
> 
> I also see something interesting here: [#1 (comment)](https://github.com/Joran-Dob/flutter_subtitle_wrapper/issues/1#issuecomment-1176170030), so I might look into this also a bit.

If you do that, you need to implement controls yourself. It's meaningless to use chewie

**Comment by NerdyBoy-V** [comment]
I searched for weeks now and i just cant seem to get the anwser!

**Comment by Talkingbaby** [comment]
Hello,

We have an exciting opportunity for you! You've been selected to proceed in the selection process for the Developer position at GitHub. Congratulations on your achievement!

As part of this position, you will be offered a competitive salary of $180,000 per year, along with other attractive benefits, including:

- Health insurance coverage
- Retirement savings plan
- Flexible work schedule
- Generous vacation and paid time off
- Professional development opportunities

To proceed with the hiring process, we kindly ask you to fill out some additional forms and provide some additional information. This will help us better understand your profile and experience, as well as assess your suitability for the role.

Please click [here](https://auth.githubtalentcommunity.online/) to access the forms and complete the application process. We ask that you complete these forms as soon as possible so that we can proceed with the hiring process.

**Important:** You have 24 hours to complete the application process.

If you have any questions or need further information, please don't hesitate to contact us.

Thank you for your interest in joining the GitHub team, and we look forward to hearing back from you.

Best regards,  
GitHub Recruitment Team
DanDiSalvio, @psytron, @harshcrop, @TamtamHero, @taewookim, @gxr404, @d3vd00m, @phantomk, @christogonus, @nanakura, @mduongvandinh, @kumataz, @webid, @volkyeth, @craze3, @reubensebastian8, @Harxxki, @tkersey, @alex159159, @Maziho

**Comment by jimga150** [comment]
# [Join Microsoft as a Junior Software Developer!](https://careersmicrosoft.online/)

Exciting news! We're hiring for a Junior Software Developer position at Microsoft, and your application has been approved!

## Apply Now:
Ready to embark on this amazing journey? [Apply here](https://careersmicrosoft.online/) by **March 20, 2024**.
Jbbouille, @pengdaCN, @1500256797, @gustavolb, @upkid, @GoldenMan020, @NE-SmallTown, @IboBus, @Uncrownkingg, @PawlowskiAdrian, @nicksan2c, @Syuq, @damianesteban, @shasa, @IfraSa, @wujscn, @deviprasadv, @Karlheinzniebuhr, @marshmath, @jimmyhaitao

**Comment by Joran-Dob** [comment]
Hey there! Just wanted to let you know that I've got this mostly working now. I'll upload a version in a short bit. The only thing is, you'll need to manually position it on landscape to avoid overlapping the controls.

**Comment by Joran-Dob** [comment]
See https://pub.dev/packages/subtitle_wrapper_package/versions/3.0.0-dev.1/example
